### PR TITLE
Improved the running and capturing output of idevice_id.exe. Removed expired cert.

### PR DESCRIPTION
**Pull request by CrazeeGhost**

### CODE REVIEW

**Comment by DiscordDigital** [comment]
How is that better? Also the certificate isn't expired. Run Unblock-File on the script, make sure you've ExecutionPolicy set to RemoteSigned.

**Comment by CrazeeGhost** [comment]
Your method of capturing the output from idevice_id.exe was returning false positives after a device had been found then gone back to being not found again. 
I tried unblocking the file and setting the ExecutionPolicy  to RemoteSigned and it still didn't work for me.

**Comment by DiscordDigital** [comment]
Strange, it worked for me on another machine without issues. Did you clone to desktop? When you copy from raw, the line endings will be wrong.

**Comment by DiscordDigital** [comment]
Feel free to create a pull request where only the method of capturing the output from idevice_id.exe is changed. Then I'll accept the pull request.

**Comment by CrazeeGhost** [comment]
Done. Retracted the earlier pull request and created a new one. Thanks

________________________________

**Pull request closed without merging**
